alter table books add column image_url varchar;
alter table books add column small_image_url varchar;
alter table books add column books_count numeric;
alter table books add column isbn13 varchar;
alter table books add column isbn varchar;
alter table books add column original_publication_year varchar;
alter table books add column original_title varchar;
alter table books add column language_code varchar;
alter table books add column average_rating numeric;