
CREATE TABLE IF NOT EXISTS orders
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    address_id bigint NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT fkhlglkvf5i60dv6dn397ethgpt FOREIGN KEY (address_id)
        REFERENCES addresses (id)
)