create table orders
(id bigint generated by default as identity,
 quantity numeric not null,
 order_date timestamp not null,
 payment_mode varchar(30) not null,
 user_id bigint not null,
 address_id bigint not null,
 book_id bigint not null,
 primary key (id))
